apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nginx
  namespace: argocd
  annotations:
    argocd-image-updater.argoproj.io/image-list: bucket23/nginx-demo
    argocd-image-updater.argoproj.io/write-back-method: git
    argocd-image-updater.argoproj.io/git-branch: main
    argocd-image-updater.argoproj.io/nginx.values-file: nginx/values.yaml
    argocd-image-updater.argoproj.io/nginx.value-path: image.tag
spec:
  project: default
  source:
    repoURL: https://github.com/Arpit-Sharma-as/nginx-demo.git
    path: nginx
    targetRevision: feature/k8s
    helm:
      valueFiles:
        - nginx/values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
