apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-image-updater-config
  namespace: argocd
data:
  config.yaml: |
    log:
      level: debug
    registries.conf: |
  registries:
    - name: DockerHub
      prefix: docker.io
      credentials: dockerhub-creds
      default: true
